In [1]:
import tensorflow as tf

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston_data = load_boston()

In [4]:
boston_data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [6]:
boston_data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [46]:
boston_data.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [7]:
boston_data.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
data = boston_data.data

In [9]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

array([6.4170e-02, 0.0000e+00, 5.9600e+00, 0.0000e+00, 4.9900e-01,
       5.9330e+00, 6.8200e+01, 3.3603e+00, 5.0000e+00, 2.7900e+02,
       1.9200e+01, 3.9690e+02, 9.6800e+00])

In [ ]:
pipeline

In [10]:
output = boston_data.target

In [11]:
output

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [12]:
import numpy as np

In [14]:
def data_normalization(data):
    average = np.mean(data, axis=0)
    standard_deviation = np.std(data, axis=0)
    return (data-average)/standard_deviation

In [15]:
normalized_data = data_normalization(data)

In [16]:
normalized_data

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [18]:
training_rows = normalized_data.shape[0]
training_rows

506

In [19]:
training_columns = normalized_data.shape[1]
training_columns

13

In [20]:
reshaped_data = np.reshape(np.c_[np.ones(training_rows), normalized_data], [training_rows, training_columns + 1])

In [21]:
reshaped_data

array([[ 1.        , -0.41978194,  0.28482986, ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [ 1.        , -0.41733926, -0.48772236, ..., -0.30309415,
         0.44105193, -0.49243937],
       [ 1.        , -0.41734159, -0.48772236, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ...,  1.17646583,
         0.44105193, -0.98304761],
       [ 1.        , -0.40776407, -0.48772236, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [ 1.        , -0.41500016, -0.48772236, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [23]:
reshaped_output = np.reshape(output, [training_rows, 1])

In [24]:
reshaped_output

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [27]:
indices = np.random.rand(len(reshaped_data))<0.80

In [28]:
indices

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True, False,  True, False,  True,  True, False,  True, False,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False,  True, False,
        True,  True,

In [29]:
X_train, x_test, Y_train, y_test = reshaped_data[indices], reshaped_data[~indices], reshaped_output[indices], reshaped_output[~indices]

In [58]:
learning_rate = 0.15
training_epochs = 100
cost_history = np.empty(shape=[1],dtype=float)

In [59]:
training_columns = reshaped_data.shape[1]

In [60]:
training_columns

14

In [61]:
X = tf.placeholder(tf.float32,[None,training_columns])
Y = tf.placeholder(tf.float32,[None,1])
W = tf.Variable(tf.ones([training_columns,1]))

In [62]:
init = tf.global_variables_initializer()

In [63]:
y_ = tf.matmul(X, W)
cost = tf.reduce_mean(tf.square(y_ - Y))
training_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [64]:
sess = tf.Session()
sess.run(init)

In [78]:
x_test[90]

array([ 1.        ,  2.4941782 , -0.48772236,  1.01599907, -0.27259857,
        1.19472373, -0.42402741,  1.11749449, -1.04877969,  1.66124525,
        1.53092646,  0.80657583,  0.44105193,  1.97882444])

In [79]:
x_test[90] = np.array([ 1.,  3.4941782, 0.50772236,  2.3, -0.27259857,
        1.19472373, -0.42402741,  1.11749449, -1.04877969,  1.66124525,
        1.53092646,  0.80657583,  0.44105193,  1.97882444])

In [80]:
for epoch in range(training_epochs):
    sess.run(training_step,feed_dict={X:X_train,Y:Y_train})
    cost_history = np.append(cost_history,sess.run(cost,feed_dict={X:X_train,Y:Y_train}))
    pred_y = sess.run(y_, feed_dict={X:x_test})
    mse = tf.reduce_mean(tf.square(pred_y - y_test))
    print("MSE: %.4f" % sess.run(mse))

MSE: 22.1735
MSE: 22.1770
MSE: 22.1804
MSE: 22.1838
MSE: 22.1871
MSE: 22.1904
MSE: 22.1936
MSE: 22.1967
MSE: 22.1999
MSE: 22.2029
MSE: 22.2060
MSE: 22.2089
MSE: 22.2118
MSE: 22.2147
MSE: 22.2176
MSE: 22.2203
MSE: 22.2231
MSE: 22.2258
MSE: 22.2284
MSE: 22.2310
MSE: 22.2336
MSE: 22.2361
MSE: 22.2386
MSE: 22.2411
MSE: 22.2435
MSE: 22.2459
MSE: 22.2482
MSE: 22.2505
MSE: 22.2528
MSE: 22.2550
MSE: 22.2572
MSE: 22.2593
MSE: 22.2615
MSE: 22.2636
MSE: 22.2656
MSE: 22.2676
MSE: 22.2696
MSE: 22.2716
MSE: 22.2735
MSE: 22.2754
MSE: 22.2772
MSE: 22.2791
MSE: 22.2809
MSE: 22.2826
MSE: 22.2844
MSE: 22.2861
MSE: 22.2878
MSE: 22.2894
MSE: 22.2910
MSE: 22.2926
MSE: 22.2942
MSE: 22.2958
MSE: 22.2973
MSE: 22.2988
MSE: 22.3003
MSE: 22.3017
MSE: 22.3031
MSE: 22.3045
MSE: 22.3059
MSE: 22.3073
MSE: 22.3086
MSE: 22.3099
MSE: 22.3112
MSE: 22.3125
MSE: 22.3137
MSE: 22.3149
MSE: 22.3161
MSE: 22.3173
MSE: 22.3185
MSE: 22.3196
MSE: 22.3208
MSE: 22.3219
MSE: 22.3230
MSE: 22.3240
MSE: 22.3251
MSE: 22.3261
MSE: 22.3271

In [66]:
pred_y = sess.run(y_, feed_dict={X: x_test})
mse = tf.reduce_mean(tf.square(pred_y - y_test))
print("MSE: %.4f" % sess.run(mse))

MSE: 22.1513


In [81]:
x_test[90]

array([ 1.        ,  3.4941782 ,  0.50772236,  2.3       , -0.27259857,
        1.19472373, -0.42402741,  1.11749449, -1.04877969,  1.66124525,
        1.53092646,  0.80657583,  0.44105193,  1.97882444])

In [82]:
y_test[90]

array([5.6])

In [84]:
pred_y[90]

array([11.297186], dtype=float32)